### ISSUE TITLE
Consistent naming scheme

### ISSUE THREAD

**Issue by asbjornu** [Data-Protection-Control/ADPC#8]
The current draft uses both `camelCase` and `snake_case` as per the following example:

```json
{
  "consentRequests": {
    "cookies": "Store and/or access cookies on your device.",
    "ads_profiling": "Create a personalised ads profile."
  }
}
```

Please consider choosing one naming scheme and use that consistently. Since JSON derives from JavaScript, which in turn uses `camelCase`, I'd recommend to go with that, but no matter which casing you choose, please only use one. Converted to `camelCase` the above example would look like this:

```json
{
  "consentRequests": {
    "cookies": "Store and/or access cookies on your device.",
    "adsProfiling": "Create a personalised ads profile."
  }
}
```

**Comment by coolharsh55** [comment]
+1 for camelCase; however the request IDs may themselves be derived from an external source and follow their own conventions. So a note in the document about use of camelCase as a _preference_ would be ideal. I can create a PR to add this.

**Comment by gb-noyb** [comment]
Thanks for the sharp-eyed observation. I agree that specification itself should be consistent in the names it defines, and keys like `consentRequests` are indeed camelCased. The request identifiers, as Harshvardhan mentions, are up for the website to choose. I don’t think it’s up to us to tell websites which faction to join, but I suppose we can try give ‘a good example’. Happy either way, so since there is a PR lying here already I’ll just apply this suggestion.
